// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmoNCZqv5KQUe6zWZ4uwTl_NBm4Jg1N7E',
    appId: '1:1087977468125:web:972f83c891d83a5eb82b34',
    messagingSenderId: '1087977468125',
    projectId: 'flutter-folio-6f5bf',
    authDomain: 'flutter-folio-6f5bf.firebaseapp.com',
    storageBucket: 'flutter-folio-6f5bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzrffAj5bJ2o-9l_S5a7hH_mGFHqYnsYY',
    appId: '1:1087977468125:android:c8961fb9816853fab82b34',
    messagingSenderId: '1087977468125',
    projectId: 'flutter-folio-6f5bf',
    storageBucket: 'flutter-folio-6f5bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn7bcZrxkN1DZsRCJj7cAGKLdPsbTvi-4',
    appId: '1:1087977468125:ios:f80612926c9679aab82b34',
    messagingSenderId: '1087977468125',
    projectId: 'flutter-folio-6f5bf',
    storageBucket: 'flutter-folio-6f5bf.appspot.com',
    iosClientId: '1087977468125-mgfbgsr1voo6iposk4dqvuc2ua76b20e.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn7bcZrxkN1DZsRCJj7cAGKLdPsbTvi-4',
    appId: '1:1087977468125:ios:f80612926c9679aab82b34',
    messagingSenderId: '1087977468125',
    projectId: 'flutter-folio-6f5bf',
    storageBucket: 'flutter-folio-6f5bf.appspot.com',
    iosClientId: '1087977468125-mgfbgsr1voo6iposk4dqvuc2ua76b20e.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFolio',
  );
}
